name: primesse_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.0
  fluentui_system_icons: ^1.1.221
  flutter_spinkit: ^5.2.0
  http: ^0.13.6
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  image_gallery_saver: ^2.0.3
  just_audio: ^0.9.35
  rxdart: ^0.27.7
  audio_video_progress_bar: ^2.0.1
  url_launcher: ^6.2.1
  intl: ^0.18.1
  photo_view: ^0.14.0
  cached_network_image: ^3.3.0
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.14.0
  shared_preferences: ^2.2.2
  flutter_cache_manager: ^3.3.1
  google_nav_bar: ^5.0.6
  staggered_grid_view_flutter: ^0.0.4
  device_information: ^0.0.4
  device_info_plus: ^9.1.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/PM_ICON.png"
    
flutter:
  uses-material-design: true
  assets:
    - assets/
    
  fonts: 
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800