class ChatUsers {
  String name;
  String messageText;
  String imageURL;
  String hashtag;
  String twitter;
  bool isFav;
  ChatUsers(
      {required this.name,
      required this.messageText,
      required this.imageURL,
      required this.hashtag,
      required this.twitter,
      required this.isFav});
}

List<ChatUsers> chatUsers = [
  ChatUsers(
      name: "Adel",
      imageURL: "assets/Adel.jpg",
      messageText: "Generasi 8",
      hashtag: "JawabDel",
      twitter:"@R_AdelJKT48",
      isFav: false),
  ChatUsers(
      name: "Alya",
      imageURL: "assets/Alya.jpg",
      messageText: "Generasi 11",
      hashtag: "AlbalesYa",
      twitter:"@AA_AlyaJKT48",
      isFav: false),
  ChatUsers(
      name: "Amanda",
      imageURL: "assets/Amanda.jpg",
      messageText: "Generasi 10",
      hashtag: "Mandaily",
      twitter:"@PS_AmandaJKT48",
      isFav: false),
  ChatUsers(
      name: "Anindya",
      imageURL: "assets/Anindya.jpg",
      messageText: "Generasi 11",
      hashtag: "ANINotes",
      twitter:"@AR_AnindyaJKT48",
      isFav: false),
  ChatUsers(
      name: "Ashel",
      imageURL: "assets/Ashel.jpg",
      messageText: "Graduate",
      hashtag: "Ashelpm",
      twitter:"@S_AshelJKT48",
      isFav: false),
  ChatUsers(
      name: "Callie",
      imageURL: "assets/Callie.jpg",
      messageText: "Generasi 10",
      hashtag: "CallieAnswer",
      twitter:"@AW_CallieJKT48",
      isFav: false),
  ChatUsers(
      name: "Cathy",
      imageURL: "assets/Cathy.jpg",
      messageText: "Generasi 11",
      hashtag: "ChitCath",
      twitter:"@N_CathyJKT48",
      isFav: false),
  ChatUsers(
      name: "Chelsea",
      imageURL: "assets/Chelsea.jpg",
      messageText: "Generasi 11",
      hashtag: "Matessage",
      twitter:"@DC_ChelseaJKT48",
      isFav: false),
  ChatUsers(
      name: "Chika",
      imageURL: "assets/Chika.jpg",
      messageText: "Graduate",
      hashtag: "chaTamara",
      twitter:"@Y_ChikaJKT48",
      isFav: false),
  ChatUsers(
      name: "Christy",
      imageURL: "assets/Christy.jpg",
      messageText: "Generasi 7",
      hashtag: "ChriStory",
      twitter:"@A_ChristyJKT48",
      isFav: false),
  ChatUsers(
      name: "Cynthia",
      imageURL: "assets/Cynthia.jpg",
      messageText: "Generasi 11",
      hashtag: "NgebuCyn",
      twitter:"@Y_CynthiaJKT48",
      isFav: false),
  ChatUsers(
      name: "Daisy",
      imageURL: "assets/Daisy.jpg",
      messageText: "Generasi 11",
      hashtag: "DaisyLetter",
      twitter:"@Daisy_JKT48",
      isFav: false),
  ChatUsers(
      name: "Danella",
      imageURL: "assets/Danella.jpg",
      messageText: "Generasi 11",
      hashtag: "DenAnswer",
      twitter:"@Danella_JKT48",
      isFav: false),
  ChatUsers(
      name: "Eli",
      imageURL: "assets/Eli.jpg",
      messageText: "Generasi 7",
      hashtag: "ELIne",
      twitter:"@H_EliJKT48",
      isFav: false),
  ChatUsers(
      name: "Elin",
      imageURL: "assets/Elin.jpg",
      messageText: "Generasi 11",
      hashtag: "StoryThelin",
      twitter:"@Elin_JKT48",
      isFav: false),
  ChatUsers(
      name: "Ella",
      imageURL: "assets/Ella.jpg",
      messageText: "Generasi 10",
      hashtag: "AnswerElla",
      twitter:"@AM_EllaJKT48",
      isFav: false),
  ChatUsers(
      name: "Feni",
      imageURL: "assets/Feni.jpg",
      messageText: "Generasi 3",
      hashtag: "FeniMail",
      twitter:"@F_FeniJKT48",
      isFav: false),
  ChatUsers(
      name: "Fiony",
      imageURL: "assets/Fiony.jpg",
      messageText: "Generasi 8",
      hashtag: "FionyMail",
      twitter:"@A_FionyJKT48",
      isFav: false),
  ChatUsers(
      name: "Flora",
      imageURL: "assets/Flora.jpg",
      messageText: "Generasi 8",
      hashtag: "WordsForFlora",
      twitter:"@S_FloraJKT48",
      isFav: false),
  ChatUsers(
      name: "Freya",
      imageURL: "assets/Freya.jpg",
      messageText: "Generasi 7",
      hashtag: "FreyTalk",
      twitter:"@Freya_JKT48",
      isFav: false),
  ChatUsers(
      name: "Gendis",
      imageURL: "assets/Gendis.jpg",
      messageText: "Generasi 11",
      hashtag: "GendisTalk",
      twitter:"@Gendis_JKT48",
      isFav: false),
  ChatUsers(
      name: "Gita",
      imageURL: "assets/Gita.jpg",
      messageText: "Generasi 6",
      hashtag: "GiTalk",
      twitter:"@A_GitaJKT48",
      isFav: false),
  ChatUsers(
      name: "Gracia",
      imageURL: "assets/Gracia.jpg",
      messageText: "Generasi 3",
      hashtag: "GREPly",
      twitter:"@S_GraciaJKT48",
      isFav: false),
  ChatUsers(
      name: "Gracie",
      imageURL: "assets/Gracie.jpg",
      messageText: "Generasi 11",
      hashtag: "Ciedibales",
      twitter:"@Gracie_JKT48",
      isFav: false),
  ChatUsers(
      name: "Greesel",
      imageURL: "assets/Greesel.jpg",
      messageText: "Generasi 11",
      hashtag: "GreeThings",
      twitter:"@Greesel_JKT48",
      isFav: false),
  ChatUsers(
      name: "Indah",
      imageURL: "assets/Indah.jpg",
      messageText: "Generasi 9",
      hashtag: "BalesIndah",
      twitter:"@C_IndahJKT48",
      isFav: false),
  ChatUsers(
      name: "Indira",
      imageURL: "assets/Indira.jpg",
      messageText: "Generasi 10",
      hashtag: "DearDira",
      twitter:"@SP_IndiraJKT48",
      isFav: false),
  ChatUsers(
      name: "Jeane",
      imageURL: "assets/Jeane.jpg",
      messageText: "Generasi 11",
      hashtag: "JeanEmail",
      twitter:"@Jeane_JKT48",
      isFav: false),
  ChatUsers(
      name: "Jessi",
      imageURL: "assets/Jessi.jpg",
      messageText: "Generasi 7",
      hashtag: "JawabJeci",
      twitter:"@C_JessiJKT48",
      isFav: false),
  ChatUsers(
      name: "Kathrina",
      imageURL: "assets/Kathrina.jpg",
      messageText: "Generasi 9",
      hashtag: "CHATrina",
      twitter:"@I_KathrinaJKT48",
      isFav: false),
  ChatUsers(
      name: "Lia",
      imageURL: "assets/Lia.jpg",
      messageText: "Generasi 10",
      hashtag: "LiaChat",
      twitter:"@AU_LiaJKT48",
      isFav: false),
  ChatUsers(
      name: "Lulu",
      imageURL: "assets/Lulu.jpg",
      messageText: "Generasi 8",
      hashtag: "LLChat",
      twitter:"@A_LuluJKT48",
      isFav: false),
  ChatUsers(
      name: "Lyn",
      imageURL: "assets/Lyn.jpg",
      messageText: "Generasi 10",
      hashtag: "KabarLyn",
      twitter:"@SE_LynJKT48",
      isFav: false),
  ChatUsers(
      name: "Marsha",
      imageURL: "assets/Marsha.jpg",
      messageText: "Generasi 9",
      hashtag: "PuntenSha",
      twitter:"@L_MarshaJKT48",
      isFav: false),
  ChatUsers(
      name: "Michie",
      imageURL: "assets/Michie.jpg",
      messageText: "Generasi 11",
      hashtag: "PerMichie",
      twitter:"@Michie_JKT48",
      isFav: false),
  ChatUsers(
      name: "Muthe",
      imageURL: "assets/Muthe.jpg",
      messageText: "Generasi 7",
      hashtag: "DearMuthe",
      twitter:"@A_MutheJKT48",
      isFav: false),
  ChatUsers(
      name: "Olla",
      imageURL: "assets/Olla.jpg",
      messageText: "Generasi 7",
      hashtag: "SendToOlali",
      twitter:"@F_OllaJKT48",
      isFav: false),
  ChatUsers(
      name: "Oniel",
      imageURL: "assets/Oniel.jpg",
      messageText: "Generasi 8",
      hashtag: "NielBalesNiel",
      twitter:"@C_OnielJKT48",
      isFav: false),
  ChatUsers(
      name: "Raisha",
      imageURL: "assets/Raisha.jpg",
      messageText: "Generasi 10",
      hashtag: "Raiply",
      twitter:"@SW_RaishaJKT48",
      isFav: false),
  ChatUsers(
      name: "Shani",
      imageURL: "assets/Shani.jpg",
      messageText: "Generasi 3",
      hashtag: "PeShan",
      twitter:"@N_ShaniJKT48",
      isFav: false),
  ChatUsers(
      name: "Zee",
      imageURL: "assets/Zee.jpg",
      messageText: "Generasi 7",
      hashtag: "ZeeLetter",
      twitter:"@A_ZeeJKT48",
      isFav: false),
];
